title: Моя страница
author: Листик
email: YanaZkharova1990@mail.ru
description: > # this means to ignore newlines until "baseurl:"
  Прохожу обучение на GitHub...
# social links
twitter_username:  jiucmuk
github_username:  Jlucmuk

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
